<div class="jumbotron">
    <h1>SUMO-sim RA</h1>
    <p>Simple analyzer for SUMO simulation results.</p>
    <h4>Step 1: upload data files</h4>
    <h4>Step 2: enjoy data presentation</h4><br />
    <p><a class="btn btn-primary btn-lg" href="<?php echo $this->url(['controller'=>'analyzer']); ?>" role="button">Get strated</a></p><br />
    <p><a href="https://github.com/malakhaltsev/SUMO_analyzer">GitHub project</a></p>
    <p><a href="http://www.dlr.de/ts/en/desktopdefault.aspx/tabid-9883/16931_read-41000/">Learn more about SUMO</a></p>
</div>